### ISSUE TITLE
E/COULD NOT FIND HELPER WITH KEY( 2462): 2342

### ISSUE THREAD

**Issue by amdkholil** [abdallah-odeh/flutter_file_downloader#34]
Hi @abdallah-odeh 

currently I using `flutter_file_downloader 1.2.1`, and got this message when downloading file, file not downloaded and no error appear from `onDownloadError`

this is debug show:
![image](https://github.com/abdallah-odeh/flutter_file_downloader/assets/29882551/152da01c-0e37-46ff-85e7-acbea37a9ba9)

and this is my code:
![image](https://github.com/abdallah-odeh/flutter_file_downloader/assets/29882551/177f6617-0f64-4891-984f-4ed3411e2e10)

can you help me please?

Thank you..

**Comment by abdallah-odeh** [comment]
Hello @amdkholil 
Of course I will do my best to help
Actually you are not the first one who posts this issue, but in the last time I could not reproduce it
Does it happen always? I mean every time you try to download a file it gives you this error?

**Comment by amdkholil** [comment]
thank you @abdallah-odeh,

yes this is always happen  every time I try to download, and it's not caught by the `onDownloadError` callback.

additionally this is the result of my `flutter doctor` :
![image](https://github.com/abdallah-odeh/flutter_file_downloader/assets/29882551/7cfd19be-7da2-4e4a-8641-a99e919ea825)

**Comment by abdallah-odeh** [comment]
it's not caught be `onDownloadError` because the callbacks were not found by the native code

I will try to reproduce it with the code you provided & keep you updated

**Comment by abdallah-odeh** [comment]
can you please provide me with the device's android version or SDK?

**Comment by abdallah-odeh** [comment]
@amdkholil I could not reproduce this issue :(
I tried on multiple devices in the image (Pixel, Pixel_3a_API..., Pixel C), all of them worked fine
I also used android 14, also works as expected
Can you please try your case in the example project & tell me the result

If it worked then there is some config probably in your project makes the library fail so we will be trying to find differences between sample project 
but if it didn't work, we need to wait for the next version; I am refactoring the code to solve this issue #25 to see if the problem persist

Thank you helping in improving this plugin

**Comment by abdallah-odeh** [comment]
Hello @Yogabayu
is this issue persist? I mean whenever you try to download a file this error shows up!
also you should see the downloaded file in your Downloads/ dir, can you confirm that?
this issue is only about finalizing the download task and remove it from memory (so your file is either downloaded or failed to download)

It would be amazing if you provide me with a sample code to reproduce the issue

**Comment by Yogabayu** [comment]
Hi, i got my file on download folder, but that error still showing up, even i use onDownloadCompleted or not. this is my code

```
FileDownloader.downloadFile(
                                        url: ApiEndPoints.draftUrl +
                                            draft.file!.trim(),
                                        onProgress: (name, progress) {
                                          setState(() {
                                            _progress = progress;
                                          });
                                        },
                                        onDownloadCompleted: (value) async {
                                          setState(() {
                                            _progress = null;
                                          });
                                          await openFile(value);

                                        },
                                      );
```

**Comment by abdallah-odeh** [comment]
This bug is actually driving me crazy 😅
I tried your code, changing the url only, but the `onDownloadCompleted` was triggered and the error did not show up!
I am currently refactoring the code & trying to solve as much issues as I can, but this bug, I could not reproduce it or catch it
I traced the code and found no issues that might cause it to happen!
It would be great if you guys can create a sample repo & provide me with a code that produce this issue

thank you for collaboration

**Comment by Yogabayu** [comment]
ohh i have tested my code on production server normally (when i use onDownloadCompleted value it returns correct path to my downloaded file, even that error still appears), but on my development server the error appears and doesn't return onDownloadCompleted value (address to the downloaded file). I don't know how that happens, all the servers I have are the same.

**Comment by abdallah-odeh** [comment]
returns the correct path & shows the error? actually this might the cause of the bug
because download is a stream, the progress 100 means download is completed, and if that is triggered twice, the first time it will call your `onDownloadCompleted` and terminate the task, in the second time, it will not find the task to terminate! and this can be ignored because the process went peacefully
so basically that might be the reason for firing this error

but not triggering your `onDownloadCompleted` and showing the error, this is the real bug & this is the case I was trying to reproduce
I believe that it's not server-related & there is an issue in my code but I really can't figure out how to find it

**Comment by abdallah-odeh** [comment]
hello @amdkholil & @Yogabayu, 
I deployed a new dev version `flutter_file_downloader: ^2.0.0-dev.1`
in this version I refactored the code & this issue should not occur anymore

can you please take the time to test it out before rolling it to production!

thanks in advance
