### ISSUE TITLE
I found a problem, that is, the download progress has a large span, 0->30->80->100. If it increases from 0-100 at a constant speed, the experience will be much better.

### ISSUE THREAD

**Issue by xiongzhaoxu** [abdallah-odeh/flutter_file_downloader#35]
I found a problem, that is, the download progress has a large span, 0->30->80->100. If it increases from 0-100 at a constant speed, the experience will be much better.

**Comment by abdallah-odeh** [comment]
Hello @xiongzhaoxu 
Unfortunately, I can't play with the download progress speed, It depends on the network speed for the user, server speed, etc..
also the `DownloadManager` which is currently used in the native code, only gives total size & downloaded size
I only attach a listener `Broadcast` to the `DownloadManager` instance and it fires the progress event only when it gets a chunk of the file, this chunk might differ during the download progress, specially if the server is facing heavy traffic or your connection is not stable

but I guess that the gap between progress steps you are facing as follow:
0 -> 30 because at first, you need to establish the request itself to the server
30 - 80 -> here, you got the request established and the stream is active, so a bigger chuck of the file has been received
80 -> 100 this is not considered as a big jump unless the file is very large

**Comment by abdallah-odeh** [comment]
If you have any questions or notes please feel free to reopen this issue or file a new one
